package com.a11y.auditor.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;
import jakarta.mail.internet.MimeMessage;
import org.springframework.mail.javamail.MimeMessageHelper;
@Service
public class EmailService {

    @Autowired
    private JavaMailSender mailSender;

    public void sendAuditCompletionEmail(String toEmail, String auditUrl, int violations) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");

            helper.setTo(toEmail);
            helper.setSubject("Scan Complete: " + auditUrl);

            // Simple HTML Template
            String htmlContent = """
                        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #eee; padding: 20px; border-radius: 10px;">
                            <h2 style="color: #0d6efd;">A11yInsights Report</h2>
                            <p>The accessibility scan for <strong>%s</strong> is now complete.</p>
                    
                            <div style="background-color: #f8f9fa; padding: 15px; border-radius: 8px; margin: 20px 0; text-align: center;">
                                <span style="font-size: 14px; color: #6c757d; text-transform: uppercase;">Violations Found</span>
                                <h1 style="margin: 5px 0; color: %s;">%d</h1>
                            </div>
                    
                            <p>Click the button below to view the full issue log and download your PDF report.</p>
                    
                            <div style="text-align: center; margin-top: 30px;">
                                <a href="http://localhost:5173/dashboard" 
                                   style="background-color: #0d6efd; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold;">
                                   View Full Results
                                </a>
                            </div>
                    
                            <hr style="margin-top: 40px; border: 0; border-top: 1px solid #eee;">
                            <p style="font-size: 12px; color: #adb5bd; text-align: center;">
                                Generated by A11yAuditor Engine • 2026
                            </p>
                        </div>
                    """.formatted(
                    auditUrl,
                    violations > 0 ? "#dc3545" : "#198754",
                    violations
            );

            helper.setText(htmlContent, true); // The 'true' flag makes it HTML
            mailSender.send(message);

        } catch (Exception e) {
            System.err.println("Failed to send HTML email: " + e.getMessage());
        }
    }
}